### ISSUE TITLE
deploy.bat

### ISSUE THREAD

**Issue by yalov** [yalov/CommunityPartsTitles#1]
Hi @linuxgurugamer, is running `.bat` in the PostBuildEvent in VS different from double-clicking `.bat` or launching from cmd?

I am trying to use your **buildRelease.bat** for non-Visual-Studio mod [release.bat](https://github.com/yalov/CommunityPartsTitles/blob/master/release.bat), but JD makes memory read error.

**Comment by linuxgurugamer** [comment]
Probably won't work, since it depends on parameters being passed in on the command line
