### ISSUE TITLE
MM version is old

### ISSUE THREAD

**Issue by theJesuit** [yalov/CommunityPartsTitles#24]
Hi yalov,

Not a real issue, but the version of MM that ships is old.  Latest is .4.2.3?.  I'm not great at Github, but I try make a pull request.

Thanks for this mod!  I design my own mods with respect to this one.

**Comment by yalov** [comment]
Hi, 

The last version of MM is already in the repo, 
It will be included in the next update

**Comment by minchinweb** [comment]
C.f. #21

**Comment by yalov** [comment]
closed #21
